version: "3"
services:
  starkbank-sms-login:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - SMS_API_KEY=${SMS_API_KEY}
      - LOGIN_URL=${LOGIN_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
  mongodb:
    image: mongo:3.6.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    ports:
      - "27017:27017"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ~/mongodb_data:/data/db
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
